INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('100', 'F100', 'Fokker 100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('141', 'B461', 'BAE Systems 146-100 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('142', 'B462', 'BAE Systems 146-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('143', 'B463', 'BAE Systems 146-300 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('14X', 'B461', 'BAE Systems 146-100 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('14Y', 'B462', 'BAE Systems 146-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('14Z', 'B463', 'BAE Systems 146-300 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('221', 'BCS1', 'Airbus A220-100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('223', 'BCS3', 'Airbus A220-300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('290', 'E290', 'E190-E2');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('295', 'E295', 'E195-E2');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('312', 'A310', 'Airbus A310-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('313', 'A310', 'Airbus A310-300 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('318', 'A318', 'Airbus A318');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('319', 'A319', 'Airbus A319');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('31A', 'A318', 'Airbus A318 (sharklets)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('31B', 'A319', 'Airbus A319 (sharklets)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('31N', 'A19N', 'Airbus A319neo');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('31X', 'A310', 'Airbus A310-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('31Y', 'A310', 'Airbus A310-300 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('320', 'A320', 'Airbus A320');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('321', 'A321', 'Airbus A321');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32A', 'A320', 'Airbus A320 (sharklets)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32B', 'A321', 'Airbus A321 (sharklets)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32F', 'A320', 'Airbus A320 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32N', 'A20N', 'Airbus A320neo');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32Q', 'A21N', 'Airbus A321neo');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32X', 'A321', 'Airbus A321 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('332', 'A332', 'Airbus A330-200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('333', 'A333', 'Airbus A330-300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('33X', 'A332', 'Airbus A330-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('342', 'A342', 'Airbus A340-200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('343', 'A343', 'Airbus A340-300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('345', 'A345', 'Airbus A340-500');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('346', 'A346', 'Airbus A340-600');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('351', 'A35K', 'Airbus A350-1000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('358', 'ZZZZ', 'Airbus A350-800');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('359', 'A359', 'Airbus A350-900');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('388', 'A388', 'Airbus A380-800 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('38F', 'A388', 'Airbus A380-800F Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('703', 'B703', 'Boeing 707-320B / 320C Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('70F', 'B703', 'Boeing 707-320B / 320C Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('70M', 'B703', 'Boeing 707-320B / 320C Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('717', 'B712', 'Boeing 717-200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('721', 'B721', 'Boeing 727-100 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('722', 'B722', 'Boeing 727-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('72B', 'B721', 'Boeing 727-100 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('72C', 'B722', 'Boeing 727-200 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('72W', 'B722', 'Boeing 727-200 (winglets) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('72X', 'B721', 'Boeing 727-100 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('72Y', 'B722', 'Boeing 727-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('731', 'B731', 'Boeing 737-100 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('732', 'B732', 'Boeing 737-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('733', 'B733', 'Boeing 737-300 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('734', 'B734', 'Boeing 737-400 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('735', 'B735', 'Boeing 737-500 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('736', 'B736', 'Boeing 737-600 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('738', 'B738', 'Boeing 737-800 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('739', 'B739', 'Boeing 737-900 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73C', 'B733', 'Boeing 737-300 (winglets) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73E', 'B735', 'Boeing 737-500 (winglets) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73G', 'B737', 'Boeing 737-700 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73H', 'B738', 'Boeing 737-800 (winglets) Passenger/BBJ2');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73J', 'B739', 'Boeing 737-900 (winglets) Passenger/BBJ3');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73L', 'B732', 'Boeing 737-200 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73N', 'B733', 'Boeing 737-300 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73P', 'B734', 'Boeing 737-400 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73Q', 'B734', 'Boeing 737-400 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73R', 'B737', 'Boeing 737-700 Mixed Configuration/BBJC');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73S', 'B737', 'Boeing 737-700 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73W', 'B737', 'Boeing 737-700 (winglets) Passenger/BBJ1');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73X', 'B732', 'Boeing 737-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73Y', 'B733', 'Boeing 737-300 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('741', 'B741', 'Boeing 747-100 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('742', 'B742', 'Boeing 747-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('743', 'B743', 'Boeing 747-300 / 747-100/200 SUD Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('744', 'B744', 'Boeing 747-400 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74B', 'B744', 'Boeing 747-400 Swingtail Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74C', 'B742', 'Boeing 747-200 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74D', 'B743', 'Boeing 747-300 / 747-200 SUD Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74E', 'B744', 'Boeing 747-400 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74H', 'B748', 'Boeing 747-8 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74J', 'B74D', 'Boeing 747-400 (Domestic) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74L', 'B74S', 'Boeing 747SP Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74N', 'B748', 'Boeing 747-8F Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74R', 'B74R', 'Boeing 747SR Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74T', 'B741', 'Boeing 747-100 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74U', 'B743', 'Boeing 747-300 / 747-200 SUD Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74V', 'B74R', 'Boeing 747SR Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74X', 'B742', 'Boeing 747-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('74Y', 'B744', 'Boeing 747-400 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('752', 'B752', 'Boeing 757-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('753', 'B753', 'Boeing 757-300 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('75F', 'B752', 'Boeing 757-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('75M', 'B752', 'Boeing 757-200 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('75T', 'B753', 'Boeing 757-300 (winglets) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('75W', 'B752', 'Boeing 757-200 (winglets) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('762', 'B762', 'Boeing 767-200 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('763', 'B763', 'Boeing 767-300 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('764', 'B764', 'Boeing 767-400 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('76V', 'B763', 'Boeing 767-300 (winglets) Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('76W', 'B763', 'Boeing 767-300 (winglets) Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('76X', 'B762', 'Boeing 767-200 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('76Y', 'B763', 'Boeing 767-300 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('772', 'B77L', 'Boeing 777-200/ 200ER');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('773', 'B773', 'Boeing 777-300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('779', 'B779', 'Boeing 777-900');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('77F', 'B77F', 'Boeing 777 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('77L', 'B772', 'Boeing 777-200LR');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('77W', 'B77W', 'Boeing 777-300ER');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('77X', 'B772', 'Boeing 777-200F Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('783', 'B783', 'Boeing 787-3');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('788', 'B788', 'Boeing 787-8');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('789', 'B789', 'Boeing 787-9');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('7M8', 'B38M', 'Boeing 737 Max 8');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A22', 'AN22', 'Antonov An-22');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A26', 'AN26', 'Antonov An-26');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A28', 'AN28', 'Antonov An-28 / PZL Mielec M-28 Skytruck');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A30', 'AN30', 'Antonov An-30');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A32', 'AN32', 'Antonov An-32');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A38', 'AN38', 'Antonov An-38');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A40', 'A140', 'Antonov An-140');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A4F', 'A124', 'Antonov An-124 Ruslan');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A58', 'ZZZZ', 'Antonov An-158');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A5F', 'A225', 'Antonov An-225');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('A81', 'A148', 'Antonov AN148-100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AB4', 'A30B', 'Airbus A300B2 / A300B4 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AB6', 'A306', 'Airbus A300-600 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ABB', 'A3ST', 'Airbus A300-600ST Beluga Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ABX', 'A30B', 'Airbus A300B4 / A300C4 / A300F4 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ABY', 'A306', 'Airbus A300-600 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ACP', '*', 'Twin Commander Aircraft');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ACT', '*', 'Twin (Aero) Turbo Commander / Jetprop Commander');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AGH', 'A109', 'AgustaWestland A109');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AN4', 'AN24', 'Antonov An-24');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AN7', 'AN72', 'Antonov An-72 / An-74');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ANF', 'AN12', 'Antonov An-12');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('APF', 'ZZZZ', 'BAE Systems  ATP Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('APH', '*', 'Eurocopter (Aerospatiale) SA330 Puma / AS332 Super Puma');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AR1', 'RJ1H', 'Avro RJ100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AR7', 'RJ70', 'Avro RJ70');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AR8', 'RJ85', 'Avro RJ85');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AT4', 'AT43', 'ATR 42-300 / 320');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AT7', 'AT72', 'ATR 72');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ATF', 'AT72', 'ATR 72 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ATP', 'ATP', 'BAE Systems  ATP');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ATZ', '*', 'ATR 42 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AWH', 'A139', 'AgustaWestland AW139');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('AWZ', '*', 'Augusta Westland 200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('B12', 'BA11', 'BAE Systems (BAC) One-Eleven 200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('B13', 'BA11', 'BAE Systems (BAC) One-Eleven 300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('B14', 'BA11', 'BAE Systems (BAC) One-Eleven 400 / 475');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('B15', 'BA11', 'BAE Systems (BAC) One-Eleven 500 / RomBac One-Eleven 560');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('B72', 'B720', 'Boeing 720-020B');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BE2', '*', 'Hawker Beechcraft (Light aircraft-twin piston engines)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BE4', 'BE40', 'Hawker 400 Beechjet/400A/400XP/400T');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BE9', 'BE99', 'Hawker Beechcraft C99 Airliner');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BEF', 'B190', 'Hawker Beechcraft 1900 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BEH', 'B190', 'Hawker Beechcraft 1900D Airliner');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BEP', '*', 'Hawker Beechcraft (Light aircraft-single piston engine)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BES', 'B190', 'Hawker Beechcraft 1900C Airliner');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BET', '*', 'Hawker Beechcraft (Light aircraft-twin turboprop engines)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BH2', '*', 'Bell (Helicopters)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BNI', 'BN2P', 'Britten-Norman BN-2A / BN-2B Islander');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BNT', 'TRIS', 'Britten-Norman BN-2A Mk.III Trislander');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BTA', 'ZZZZ', 'Business Turbo-Prop Aircraft');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BUS', '0000', 'Bus');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('C27', 'AJ27', 'Comac ARJ21-700');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CCJ', 'CL60', 'Canadair (Bombardier) CL-600 / 601 / 604 / 605 Challenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CCW', 'GL5T', 'Bombardier BD-700 Global 5000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CCX', 'GLEX', 'Bombardier BD-700 Global Express');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CD2', 'NOMA', 'Gippsland Aeronautics N22B / N24A Nomad');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJ1', '*', 'Cessna 500/ 501/ 525 Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJ2', '*', 'Cessna 550/ 551/ 552 Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJ5', '*', 'Cessna 560 Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJ6', '*', 'Cessna 650 Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJ8', '*', 'Cessna 680 Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJL', '*', 'Cessna 560 XL/XLS Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJM', 'C510', 'Cessna 510 Mustang Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CJX', 'C750', 'Cessna 750 Citation X');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CL3', 'CL30', 'Bombardier Challenger 300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CN1', '*', 'Cessna (Light aircraft-single piston engine)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CN2', '*', 'Cessna (Light aircraft-twin piston engines)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CNC', '*', 'Cessna (Light aircraft-single turboprop engine)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CNF', '*', 'Cessna 208B Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CNJ', '*', 'Cessna Citation');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CNT', '*', 'Cessna (Light aircraft-twin turboprop engines)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CR1', 'CRJ1', 'Canadair (Bombardier) Regional Jet 100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CR2', 'CRJ2', 'Canadair (Bombardier) Regional Jet 200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CR7', 'CRJ7', 'Canadair (Bombardier) Regional Jet 700 and Challenger 870');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CR9', 'CRJ9', 'Canadair (Bombardier) Regional Jet 900 and Challenger 890');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CRA', 'CRJ9', 'Canadair (Bombardier) Regional Jet 705');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CRF', 'ZZZZ', 'Canadair (Bombardier) Regional Jet Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CRK', 'CRJX', 'Canadair (Bombardier) Regional Jet 1000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CS2', 'C212', 'CASA / lAe 212 Aviocar');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CS5', 'CN35', 'CASA / lAe CN-235');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CS9', 'C295', 'CASA / lAe C-295');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CV2', 'CVLP', 'Convair 240 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CV4', 'CVLP', 'Convair 440 Metropolitan Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CV5', 'CVLT', 'Convair 580 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CVV', 'CVLP', 'Convair 240 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CVX', 'CVLP', 'Convair 340 / 440 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CVY', 'CVLT', 'Convair 580 / 5800 / 600 / 640 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('CWC', 'C46', 'Curtiss C-46 Commando');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D11', 'DC10', 'Boeing (Douglas) DC-10-10 / 15 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D1C', 'DC10', 'Boeing (Douglas) DC-10-30 / 40 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D1M', 'DC10', 'Boeing (Douglas) DC-10-30 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D1X', 'DC10', 'Boeing (Douglas) DC-10-10 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D1Y', 'DC10', 'Boeing (Douglas) DC-10-30 / 40 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D20', 'F2TH', 'Dassault Falcon 2000/2000DX');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D28', 'D228', 'Fairchild Dornier 228');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D2L', 'F2TH', 'Dassault Falcon 2000EX/EASY/LX');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D38', 'D328', 'Fairchild Dornier 328-100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D3F', 'DC3', 'Boeing (Douglas) DC-3 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D42', 'DA42', 'Diamond Aircraft DA42 Twin Star');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D4X', 'DH8D', 'De Havilland (Bombardier) DHC-8-400 Dash 8Q Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D6F', 'DC6', 'Boeing (Douglas) DC-6A / DC-6B / DC-6C Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D8L', 'DC86', 'Boeing (Douglas) DC-8-62 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D8M', 'DC86', 'Boeing (Douglas) DC-8-62 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D8Q', 'DC87', 'Boeing (Douglas) DC-8-72 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D8T', 'DC85', 'Boeing (Douglas) DC-8-50 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D8X', 'DC86', 'Boeing (Douglas) DC-8-61 / 62 / 63 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D8Y', 'DC87', 'Boeing (Douglas) DC-8-71 / 72 / 73 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D91', 'DC91', 'Boeing (Douglas) DC-9-10 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D92', 'DC92', 'Boeing (Douglas) DC-9-20 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D93', 'DC93', 'Boeing (Douglas) DC-9-30 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D94', 'DC94', 'Boeing (Douglas) DC-9-40 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D95', 'DC95', 'Boeing (Douglas) DC-9-50 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D9C', 'DC93', 'Boeing (Douglas) DC-9-30 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D9D', 'DC94', 'Boeing (Douglas) DC-9-40 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D9L', 'F900', 'Dassault Falcon 900LX');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('D9X', 'DC91', 'Boeing (Douglas) DC-9-10 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DC3', 'DC3', 'Boeing (Douglas) DC-3 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DC4', 'DC4', 'Boeing (Douglas) DC-4');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DC6', 'DC6', 'Boeing (Douglas) DC-6B Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DF1', 'FA10', 'Dassault Falcon 10 / 100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DF2', 'FA20', 'Dassault Falcon 20 / 200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DF5', 'FA50', 'Dassault Falcon 50 / 50EX');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DF7', 'FA7X', 'Dassault Falcon 7X');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DF9', 'F900', 'Dassault Falcon 900/900B/900C/900DX/900EX/EASY');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DH1', 'DH8A', 'De Havilland (Bombardier) DHC-8-100 Dash 8 / 8Q');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DH2', 'DH8B', 'De Havilland (Bombardier) DHC-8-200 Dash 8 / 8Q');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DH3', 'DH8C', 'De Havilland (Bombardier) DHC-8-300 Dash 8 / 8Q');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DH4', 'DH8D', 'De Havilland (Bombardier) DHC-8-400 Dash 8Q');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DH7', 'DHC7', 'De Havilland (Bombardier) DHC-7 Dash 7');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHC', 'DHC4', 'De Havilland (Bombardier) DHC-4 Caribou');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHD', 'DOVE', 'BAE Systems (De Havilland) 104 Dove');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHF', '0000', 'De Havilland (Bombardier) DHC-8 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHH', 'HERN', 'BAE Systems (De Havilland) 114 Heron');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHL', 'DH3T', 'De Havilland (Bombardier) DHC-3 Turbo Otter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHP', 'DHC2', 'De Havilland (Bombardier) DHC-2 Beaver');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHR', 'DH2T', 'De Havilland (Bombardier) DHC-2 Turbo Beaver');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHS', 'DHC3', 'De Havilland (Bombardier) DHC-3 Otter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DHT', 'DHC6', 'De Havilland (Bombardier) DHC-6 Twin Otter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('E70', 'E170', 'Embraer 170');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('E75', 'E170', 'Embraer 175');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('E90', 'E190', 'Embraer 190');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('E95', 'E190', 'Embraer 195 and Legacy 1000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EA5', 'EA50', 'Eclipse 500');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EC3', 'EC30', 'Eurocopter EC130');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EC5', 'EC55', 'Eurocopter EC155');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EM2', 'E120', 'Embraer 120 Brasilia');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EMB', 'E110', 'Embraer 110 Bandeirante');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EP1', 'E50P', 'Embraer EMB-500 Phenom 100');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('EP3', 'E55P', 'Embraer EMB-505 Phenom 300');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ER3', 'E135', 'Embraer RJ135 and Legacy 600/650');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ER4', 'E145', 'Embraer RJ145');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ERD', 'E135', 'Embraer RJ140');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F21', 'F28', 'Fokker F28 Fellowship 1000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F22', 'F28', 'Fokker F28 Fellowship 2000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F23', 'F28', 'Fokker F28 Fellowship 3000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F24', 'F28', 'Fokker F28 Fellowship 4000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F27', 'F27', 'Fokker F27 Friendship / Fairchild Industries F-27');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F50', 'F50', 'Fokker 50');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F5F', 'F50', 'Fokker 50 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('F70', 'F70', 'Fokker 70');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('FK7', 'F27', 'Fairchild Industries FH-227');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('FRJ', 'J328', 'Fairchild Dornier 328JET');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('G2B', 'GLF2', 'Gulfstream Aerospace G-1159 Gulfstream IIB');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('G2S', 'GLF2', 'Gulfstream Aerospace G-1159 Gulfstream IISP');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GA8', 'GA8', 'Gippsland Aeronautics GA8 Airvan');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GJ2', 'GLF2', 'Gulfstream Aerospace G-1159 Gulfstream II');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GJ3', 'GLF3', 'Gulfstream Aerospace G-1159A Gulfstream III');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GJ4', 'GLF4', 'Gulfstream Aerospace IV (G300/G350/G400/G450/IVSP)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GJ5', 'GLF5', 'Gulfstream Aerospace V (G500/G550)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GJ6', 'GLF6', 'Gulfstream Aerospace G650');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GR1', 'G150', 'Gulfstream Aerospace G-100/G-150 (Astra SPX)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GR2', 'GALX', 'Gulfstream Aerospace G-200 (Galaxy)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GR3', 'G280', 'Gulfstream Aerospace G-280');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GRG', 'G21', 'Grumman G-21 Goose (Amphibian)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('GRM', 'G73T', 'Grumman G-73 Turbo Mallard (Amphibian)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('H20', 'PRM1', 'Hawker 200');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('H21', 'H25C', 'Hawker 1000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('H24', 'HA4T', 'Hawker 4000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('H25', 'H25B', 'Hawker 750/800/800XP/800SP');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('H28', 'H25B', 'Hawker 850XP/900');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('H29', 'H25B', 'Hawker 900XP');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('HEC', 'COUR', 'Helio H-250 Courier / H-295 / 395 Super Courier');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('HOV', '0000', 'Surface Equipment-Hovercraft');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('HS7', 'A748', 'BAE Systems (Hawker Siddeley) 748 / Andover');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('I14', 'I114', 'Ilyushin Il-114');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('I9F', 'IL96', 'Ilyushin Il-96 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('IL6', 'IL62', 'Ilyushin Il-62');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('IL7', 'IL76', 'Ilyushin Il-76');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('IL8', 'IL18', 'Ilyushin Il-18');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('IL9', 'IL96', 'Ilyushin Il-96 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ILW', 'IL86', 'Ilyushin Il-86');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('J31', 'JS31', 'BAE Systems Jetstream 31');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('J32', 'JS32', 'BAE Systems Jetstream 32');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('J41', 'JS41', 'BAE Systems Jetstream 41');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('JU5', 'JU52', 'Junkers Ju 52/3m');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('L11', 'L101', 'Lockheed Martin L-1011 TriStar 1 / 50 / 100 / 150 / 200 / 250 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('L15', 'L101', 'Lockheed Martin L-1011 TriStar 500 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('L1F', 'L101', 'Lockheed Martin L-1011 TriStar Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('L4F', 'L410', 'Aircraft Industries (LET) 410 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('L4T', 'L410', 'Aircraft Industries (LET) 410');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LCH', '0000', 'Surface Equipment-Launch / Boat');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LJA', 'ZZZZ', 'Light Jet Aircraft');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LMO', '0000', 'Surface Equipment-Limousine');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LOE', 'L188', 'Lockheed Martin L-188 Electra');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LOF', 'L188', 'Lockheed Martin L-188 Electra Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LOH', 'C130', 'Lockheed Martin L-182 / L-282 / L-382 (L-100) Hercules');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('LRJ', '*', 'Learjet');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M11', 'MD11', 'Boeing (Douglas) MD-11 Passenger');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M1F', 'MD11', 'Boeing (Douglas) MD-11 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M1M', 'MD11', 'Boeing (Douglas) MD-11 Mixed Configuration');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M2F', 'MD82', 'Boeing (Douglas) MD82 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M3F', 'MD83', 'Boeing (Douglas) MD83 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M81', 'MD81', 'Boeing (Douglas) MD-81');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M82', 'MD82', 'Boeing (Douglas) MD-82');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M83', 'MD83', 'Boeing (Douglas) MD-83');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M87', 'MD87', 'Boeing (Douglas) MD-87');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M88', 'MD88', 'Boeing (Douglas) MD-88');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M8F', 'MD88', 'Boeing (Douglas) MD88 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('M90', 'MD90', 'Boeing (Douglas) MD-90');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('MA6', 'AN24', 'Xian Yunshuji MA-60/MA600');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('MBH', 'B105', 'Eurocopter (MBB) BO105');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('MD9', 'EXPL', 'MD Helicopters Inc MD 900 Explorer');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('MIH', 'MI8', 'Mil Mi-8 / Mi-17 / Mi-171 / Mi-172');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('MU2', 'MU2', 'Mitsubishi Aircraft Corporation MU-2');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('NDC', 'S601', 'Aerospatiale SN601 Corvette');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('NDE', '*', 'Eurocopter (Aerospatiale) AS350 Ecureuil / AS355 Ecureuil 2');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('NDH', '*', 'Eurocopter (Aerospatiale) SA365C / SA365N  Dauphin 2');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('P18', 'P180', 'Piaggio Aero P180 Avanti II');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PA1', '*', 'Piper (Light aircraft-single piston engine)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PA2', '*', 'Piper (Light aircraft-twin piston engines)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PAT', '*', 'Piper (Light aircraft-twin turboprop engines)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PL2', 'PC12', 'Pilatus PC-12');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PL6', 'PC6T', 'Pilatus PC-6 Turbo Porter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PN6', 'P68', 'Vulcanair (Partenavia) P.68');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('PR1', 'PRM1', 'Hawker 390 Premier 1/1A');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('RFS', '0000', 'Surface Equipment-Road Feeder Service (Truck)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('S20', 'SB20', 'Saab 2000');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('S58', 'S58T', 'Sikorsky S-58T');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('S61', 'S61', 'Sikorsky S-61');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('S76', 'S76', 'Sikorsky S-76');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SF3', 'SF34', 'Saab 340');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SFB', 'SF34', 'Saab 340B');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SFF', 'SF34', 'Saab 340 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SH3', 'SH33', 'Shorts 330 (SD3-30)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SH6', 'SH36', 'Shorts 360 (SD3-60)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SHS', 'SC7', 'Shorts Skyvan (SC-7)');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SU7', 'ZZZZ', 'Sukhoi Superjet 100-75');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SU9', 'SU95', 'Sukhoi Superjet 100-95');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SWF', '*', 'Fairchild (Swearingen) SA226 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SWM', '*', 'Fairchild (Swearingen) SA26 / SA226 / SA227 Merlin / Metro / Expediter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('SY8', 'AN12', 'Shaanxi Y-8');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('T20', 'T204', 'Tupolev Tu-204 / Tu-214');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('T2F', 'T204', 'Tupolev Tu-204 Freighter');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('T34', 'T334', 'Tupolev Tu-334');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('TBM', 'TBM7', 'SOCATA TBM-700');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('TRN', '0000', 'Train');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('TRS', '0000', 'Train');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('TU3', 'T134', 'Tupolev Tu-134');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('TU5', 'T154', 'Tupolev Tu-154');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('WWP', 'WW24', 'Israel Aerospace Industries 1124 Westwind');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('YK2', 'YK42', 'Yakovlev Yak-42 / Yak-142');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('YK4', 'YK40', 'Yakovlev Yak-40');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('YN2', 'Y12', 'Harbin Yunshuji Y12');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('YN7', 'AN24', 'Xian Yunshuji Y7');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('YS1', 'YS11', 'NAMC YS-11');
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('330', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('777', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('350', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('339', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('781', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('32S', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('787', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('ATR', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('767', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('737', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('7M9', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('757', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('E7W', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('7S8', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('DH8', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('BE1', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('919', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('73M', null, null);
INSERT INTO public.aircrafts (aircraft_code, airline_equip_code, model) VALUES ('747', null, null);
