global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'dst-airlines-backend'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['dst-airlines-backend:8000']
    # Note: 'dst-airlines-backend' must be reachable. 
    # If running in separate networks, we might need to adjust this.

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
